do not force MonadIO on presign
brendanhay/amazonka pull request #885
Opened 2023-01-12 21:14 UTC by avieth

2023-01-17 05:46 UTC, endgame requested changes
Since `withAuth` still has to have a `MonadIO` constraint, I'm curious what this is buying you. I see it's coming from a workplace fork, which means it's proven necessary for something, so I'm happy to merge it with a couple of tweaks.

In addition to the suggestions inline, there's a couple more changes I'll need to see before I can merge it, but those are minor:

- [ ] Add an entry to `lib/amazonka/CHANGELOG.md`
- [x] Re-export `withAuth` from `Amazonka.Auth` (as a general rule, most normal users should not have to depend directly on `amazonka-core`)

2023-01-17 05:46 UTC, endgame commented on lib/amazonka/src/Amazonka/Presign.hs
>  --
Please update the copyright year in the haddock, and remove references to `'MonadIO'` (removed here) and to `AWS specific transformers` (which have been gone for a long time).

2023-01-17 05:46 UTC, endgame commented on lib/amazonka/src/Amazonka/Presign.hs
>  -- It is intended for use directly with "Amazonka.Auth" when only presigning
```suggestion
-- It is intended for use directly with 'Amazonka.Auth.Auth' when only presigning
```

2023-01-17 05:46 UTC, endgame commented on lib/amazonka/src/Amazonka/Presign.hs
>  -- and no other AWS actions are required.
```suggestion
-- and no other AWS actions are required. See 'Amazonka.Auth.withAuth' to
-- extract an 'AuthEnv' from an 'Auth'
```

2023-01-18 22:11 UTC, endgame commented
I agree that it's a better factoring, and I hope we can merge it before I tag RC2.

2023-01-18 22:31 UTC, avieth commented
Should be good to go now. LMK if I missed anything.

2023-01-18 23:29 UTC, endgame requested changes
Couple of final nits, but I look forward to merging this today if you have time to make the changes.

2023-01-18 23:29 UTC, endgame commented on lib/amazonka/src/Amazonka/Presign.hs
> +-- It is intended for use directly with "Amazonka.Auth.Auth" when only
```suggestion
-- It is intended for use directly with 'Amazonka.Auth.Auth' when only
```

2023-01-18 23:29 UTC, endgame commented on lib/amazonka/src/Amazonka/Presign.hs
>  -- Stability   : provisional
Please update copyright year in the haddock.

2023-01-18 23:33 UTC, endgame approved these changes
Thank you very much.

2023-01-18 23:33 UTC, merged